// <auto-generated />
namespace UIWindows.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class createcampsEmissaoSaldo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(createcampsEmissaoSaldo));
        
        string IMigrationMetadata.Id
        {
            get { return "201812271709302_createcampsEmissaoSaldo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
