// <auto-generated />
namespace UIWindows.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class alter_properties_notnull_camps_sPhones_providers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(alter_properties_notnull_camps_sPhones_providers));
        
        string IMigrationMetadata.Id
        {
            get { return "201901202315570_alter_properties_notnull_camps_sPhones_providers"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
